title: "Lexi Barry — Product-Minded Data Leader"
author: "Lexi Barry"
email: "lexi.barry@outlook.com"
description: "Dashboards, Python analytics, and product storytelling using synthetic data."
meta:
  keywords: "Lexi Barry, data analytics, product management, Python, dashboards, portfolio, data storytelling, cohort analysis, A/B testing, KPI automation"
baseurl: "" # leave empty for root
url: "https://lexibarry.github.io"
github_username: "lexibarry"

# Optional for SEO (helps Google)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
